#ifndef __IEEE80211_EXTERNAL_CONFIG__H
#define __IEEE80211_EXTERNAL_CONFIG__H
#ifndef DIRECT_ATTACH
#define DIRECT_ATTACH
#endif
#ifndef ATH_AHB
#define ATH_AHB
#endif
#ifndef ATH_PCI
#define ATH_PCI
#endif
#ifndef AH_CAL_IN_FILE_HOST
#define AH_CAL_IN_FILE_HOST 1
#endif
#ifndef CALDATA0_FILE_PATH
#define CALDATA0_FILE_PATH "/tmp/wifi0.caldata"
#endif
#ifndef CALDATA1_FILE_PATH
#define CALDATA1_FILE_PATH "/tmp/wifi1.caldata"
#endif
#ifndef CALDATA2_FILE_PATH
#define CALDATA2_FILE_PATH "/tmp/wifi2.caldata"
#endif



#ifndef __LINUX_ARM_ARCH__
#define __LINUX_ARM_ARCH__ 7
#endif






#ifndef AH_BYTE_ORDER
#define AH_BYTE_ORDER AH_LITTLE_ENDIAN
#endif












#ifndef SUPPORT_11AX_D3
#define SUPPORT_11AX_D3 1
#endif
#ifndef WLAN_SUPPORT_MSCS
#define WLAN_SUPPORT_MSCS 1
#endif
#ifndef WLAN_SUPPORT_MESH_LATENCY
#define WLAN_SUPPORT_MESH_LATENCY 1
#endif
#ifndef DBS_SBS_BAND_LIMITATION_WAR
#define DBS_SBS_BAND_LIMITATION_WAR 0
#endif
#ifndef WLAN_SUPPORT_PRIMARY_ALLOWED_CHAN
#define WLAN_SUPPORT_PRIMARY_ALLOWED_CHAN 1
#endif
#ifndef SCALE_INCLUDES
#define SCALE_INCLUDES
#endif
#ifndef HOST_SW_TSO_ENABLE
#define HOST_SW_TSO_ENABLE 0
#endif
#ifndef HOST_SW_TSO_SG_ENABLE
#define HOST_SW_TSO_SG_ENABLE 1
#endif
#ifndef HOST_SW_SG_ENABLE
#define HOST_SW_SG_ENABLE 1
#endif
#ifndef HOST_SW_LRO_ENABLE
#define HOST_SW_LRO_ENABLE 0
#endif
#ifndef QCA_OL_GRO_ENABLE
#define QCA_OL_GRO_ENABLE 1
#endif
#ifndef QCA_PCIE_RESCAN
#define QCA_PCIE_RESCAN 1
#endif
#ifndef RX_CHECKSUM_OFFLOAD
#define RX_CHECKSUM_OFFLOAD 1
#endif
#ifndef TCP_CHECKSUM_OFFLOAD
#define TCP_CHECKSUM_OFFLOAD 1
#endif
#ifndef NUM_SPATIAL_STREAM
#define NUM_SPATIAL_STREAM 4
#endif
#ifndef PCI_PEREGRINE_V2_X86_WAR
#define PCI_PEREGRINE_V2_X86_WAR 0
#endif
#ifndef ATH_OL_FAST_CHANNEL_RESET_WAR
#define ATH_OL_FAST_CHANNEL_RESET_WAR 0
#endif
#ifndef OL_ATH_SUPPORT_STATS
#define OL_ATH_SUPPORT_STATS 1
#endif
#ifndef AP_MULTIPLE_BUFFER_RCV
#define AP_MULTIPLE_BUFFER_RCV 0
#endif
#ifndef ATH_SUPPORT_RX_PROC_QUOTA
#define ATH_SUPPORT_RX_PROC_QUOTA 0
#endif
#ifndef DROP_ASSOC_DURING_CSA
#define DROP_ASSOC_DURING_CSA 1
#endif
#ifndef ATH_SUPPORT_CWM
#define ATH_SUPPORT_CWM 1
#endif
#ifndef UMAC_SUPPORT_CFG80211
#define UMAC_SUPPORT_CFG80211 1
#endif
#ifndef CFG80211_SUPPORT_11AX_HOSTAPD
#define CFG80211_SUPPORT_11AX_HOSTAPD 1
#endif
#ifndef UMAC_SUPPORT_WEXT
#define UMAC_SUPPORT_WEXT 1
#endif
#ifndef UMAC_SUPPORT_WPA3_STA
#define UMAC_SUPPORT_WPA3_STA 1
#endif
#ifndef ATH_SUPPORT_AGGR_BURST
#define ATH_SUPPORT_AGGR_BURST 1
#endif
#ifndef ATH_RXBUF
#define ATH_RXBUF 512
#endif
#ifndef ATH_TXBUF
#define ATH_TXBUF 2700
#endif
#ifndef ATH_SUPPORT_UORA
#define ATH_SUPPORT_UORA 1
#endif
#ifndef ATH_SUPPORT_DFS
#define ATH_SUPPORT_DFS 1
#endif
#ifndef ATH_SUPPORT_STA_DFS
#define ATH_SUPPORT_STA_DFS 1
#endif
#ifndef QCA_SUPPORT_ETSI_PRECAC_DFS
#define QCA_SUPPORT_ETSI_PRECAC_DFS 1
#endif
#ifndef QCA_SUPPORT_BW_AGILE_DFS
#define QCA_SUPPORT_BW_AGILE_DFS 1
#endif
#ifndef ATH_SUPPORT_ZERO_CAC_DFS
#define ATH_SUPPORT_ZERO_CAC_DFS 1
#endif
#ifndef QCA_SUPPORT_ETSI_PRECAC_DFS
#define QCA_SUPPORT_ETSI_PRECAC_DFS 1
#endif
#ifndef CONFIG_16_BIT_FREQ_TYPE
#define CONFIG_16_BIT_FREQ_TYPE 1
#endif
#ifndef QCA_SUPPORT_AGILE_DFS
#define QCA_SUPPORT_AGILE_DFS 1
#endif
#ifndef WLAN_DFS_TRUE_160MHZ_SUPPORT
#define WLAN_DFS_TRUE_160MHZ_SUPPORT 1
#endif
#ifndef WLAN_DFS_PRECAC_AUTO_CHAN_SUPPORT
#define WLAN_DFS_PRECAC_AUTO_CHAN_SUPPORT
#endif
#ifndef ATH_CONVERGE_REGULATORY
#define ATH_CONVERGE_REGULATORY 1
#endif
#ifndef CONFIG_BAND_6GHZ
#define CONFIG_BAND_6GHZ 1
#endif
#ifndef DISABLE_UNII_SHARED_BANDS
#define DISABLE_UNII_SHARED_BANDS 1
#endif
#ifndef CONFIG_6G_FREQ_OVERLAP
#define CONFIG_6G_FREQ_OVERLAP 1
#endif
#ifndef WLAN_COMP_CHAN_MODE
#define WLAN_COMP_CHAN_MODE 1
#endif
#ifndef CONFIG_49GHZ_CHAN
#define CONFIG_49GHZ_CHAN 1
#endif
#ifndef REG_DISABLE_JP_CH144
#define REG_DISABLE_JP_CH144 1
#endif
#ifndef CONFIG_CHAN_FREQ_API
#define CONFIG_CHAN_FREQ_API 1
#endif
#ifndef WLAN_DFS_CHAN_HIDDEN_SSID
#define WLAN_DFS_CHAN_HIDDEN_SSID 1
#endif
#ifndef WLAN_SPECTRAL_ENABLE
#define WLAN_SPECTRAL_ENABLE 0
#endif
#ifndef WLAN_FEATURE_GPIO_CFG
#define WLAN_FEATURE_GPIO_CFG 1
#endif
#ifndef ATH_SUPPORT_VLAN
#define ATH_SUPPORT_VLAN 1
#endif
#ifndef ATH_AMSDU
#define ATH_AMSDU 1
#endif
#ifndef ATH_SUPPORT_UAPSD
#define ATH_SUPPORT_UAPSD 1
#endif
#ifndef BUILD_AP
#define BUILD_AP 1
#endif
#ifndef MIPS_TP_ENHC
#define MIPS_TP_ENHC 0
#endif
#ifndef IEEE80211_MCAST_ENHANCEMENT
#define IEEE80211_MCAST_ENHANCEMENT 1
#endif
#ifndef ATH_SUPPORT_IQUE
#define ATH_SUPPORT_IQUE 1
#endif
#ifndef ATH_SUPPORT_EXT_STAT
#define ATH_SUPPORT_EXT_STAT 1
#endif
#ifndef ATH_EXTRA_RATE_INFO_STA
#define ATH_EXTRA_RATE_INFO_STA 0
#endif
#ifndef ATH_SUPPORT_WAPI
#define ATH_SUPPORT_WAPI 1
#endif
#ifndef ATH_SUPPORT_UAPSD_RATE_CONTROL
#define ATH_SUPPORT_UAPSD_RATE_CONTROL 1
#endif
#ifndef ATH_WPS_IE
#define ATH_WPS_IE 1
#endif
#ifndef NO_SIMPLE_CONFIG
#define NO_SIMPLE_CONFIG 1
#endif
#ifndef ATH_SUPPORT_HYFI_ENHANCEMENTS
#define ATH_SUPPORT_HYFI_ENHANCEMENTS 1
#endif
#ifndef UMAC
#define UMAC
#endif
#ifndef ADF_SUPPORT
#define ADF_SUPPORT 1
#endif
#ifndef ATH_HW_TXQ_STUCK_WAR
#define ATH_HW_TXQ_STUCK_WAR 1
#endif
#ifndef ATH_SUPPORT_VOW_DCS
#define ATH_SUPPORT_VOW_DCS 1
#endif
#ifndef ATH_SUPPORT_LED
#define ATH_SUPPORT_LED 0
#endif
#ifndef OL_ATH_SUPPORT_LED
#define OL_ATH_SUPPORT_LED 1
#endif
#ifndef OL_ATH_SUPPORT_LED_POLL
#define OL_ATH_SUPPORT_LED_POLL 1
#endif
#ifndef ATH_SUPPORT_LED_CONTROLLER
#define ATH_SUPPORT_LED_CONTROLLER 1
#endif
#ifndef WLAN_SUPPORT_GREEN_AP
#define WLAN_SUPPORT_GREEN_AP 1
#endif
#ifndef WLAN_FEATURE_DISA
#define WLAN_FEATURE_DISA 1
#endif
#ifndef WLAN_FEATURE_DISA_FIPS
#define WLAN_FEATURE_DISA_FIPS 1
#endif
#ifndef IEEE80211_USE_WPA_CCMP
#define IEEE80211_USE_WPA_CCMP 1
#endif
#ifndef ATH_EXT_AP
#define ATH_EXT_AP 1
#endif
#ifndef ATH_SUPPORT_QUICK_KICKOUT
#define ATH_SUPPORT_QUICK_KICKOUT 1
#endif
#ifndef ATH_SUPPORT_IBSS
#define ATH_SUPPORT_IBSS 0
#endif
#ifndef ATH_IBSS_DFS_CHANNEL_SUPPORT
#define ATH_IBSS_DFS_CHANNEL_SUPPORT 1
#endif
#ifndef ATH_SUPPORT_EDMA
#define ATH_SUPPORT_EDMA 0
#endif
#ifndef UMAC_SUPPORT_AP_POWERSAVE
#define UMAC_SUPPORT_AP_POWERSAVE 1
#endif
#ifndef UMAC_SUPPORT_STA_POWERSAVE
#define UMAC_SUPPORT_STA_POWERSAVE 1
#endif
#ifndef UMAC_SUPPORT_POWERSAVE_QUEUE
#define UMAC_SUPPORT_POWERSAVE_QUEUE 1
#endif
#ifndef LMAC_SUPPORT_POWERSAVE_QUEUE
#define LMAC_SUPPORT_POWERSAVE_QUEUE 1
#endif
#ifndef ATH_FRAG_TX_COMPLETE_DEFER
#define ATH_FRAG_TX_COMPLETE_DEFER 0
#endif
#ifndef UMAC_SUPPORT_CCMP_SW_CRYPTO
#define UMAC_SUPPORT_CCMP_SW_CRYPTO 1
#endif
#ifndef UMAC_SUPPORT_TKIP_SW_CRYPTO
#define UMAC_SUPPORT_TKIP_SW_CRYPTO 1
#endif
#ifndef ATH_SUPPORT_WEP_MBSSID
#define ATH_SUPPORT_WEP_MBSSID 0
#endif
#ifndef UMAC_SUPPORT_RESMGR_SM
#define UMAC_SUPPORT_RESMGR_SM 0
#endif
#ifndef UMAC_SUPPORT_RESMGR
#define UMAC_SUPPORT_RESMGR 0
#endif
#ifndef UMAC_SUPPORT_RESMGR_OC_SCHED
#define UMAC_SUPPORT_RESMGR_OC_SCHED 0
#endif
#ifndef UMAC_SUPPORT_RIJNDAEL
#define UMAC_SUPPORT_RIJNDAEL 1
#endif
#ifndef UMAC_SUPPORT_ACS
#define UMAC_SUPPORT_ACS 1
#endif
#ifndef UMAC_SUPPORT_CBS
#define UMAC_SUPPORT_CBS 1
#endif
#ifndef UMAC_SUPPORT_WDS
#define UMAC_SUPPORT_WDS 1
#endif
#ifndef UMAC_SUPPORT_NAWDS
#define UMAC_SUPPORT_NAWDS 1
#endif
#ifndef UMAC_SUPPORT_STAFWD
#define UMAC_SUPPORT_STAFWD 0
#endif
#ifndef UMAC_SUPPORT_DFS
#define UMAC_SUPPORT_DFS 1
#endif
#ifndef ATH_ACL_SOFTBLOCKING
#define ATH_ACL_SOFTBLOCKING 1
#endif
#ifndef UMAC_SUPPORT_ACL
#define UMAC_SUPPORT_ACL 1
#endif
#ifndef UMAC_SUPPORT_TX_FRAG
#define UMAC_SUPPORT_TX_FRAG 1
#endif
#ifndef ATH_SUPPORT_LOWI
#define ATH_SUPPORT_LOWI 0
#endif
#ifndef UMAC_SUPPORT_IBSS
#define UMAC_SUPPORT_IBSS 0
#endif
#ifndef UMAC_REPEATER_DELAYED_BRINGUP
#define UMAC_REPEATER_DELAYED_BRINGUP 0
#endif
#ifndef ATH_SUPPORT_TxBF
#define ATH_SUPPORT_TxBF 1
#endif
#ifndef ATHEROS_LINUX_PERIODIC_SCAN
#define ATHEROS_LINUX_PERIODIC_SCAN 1
#endif
#ifndef ATHEROS_LINUX_PERIODIC_SCAN
#define ATHEROS_LINUX_PERIODIC_SCAN 1
#endif
#ifndef ATH_DEBUG
#define ATH_DEBUG 1
#endif
#ifndef ATH_VAP_PAUSE_SUPPORT
#define ATH_VAP_PAUSE_SUPPORT 1
#endif
#ifndef ATH_SUPPORT_TX_BACKLOG
#define ATH_SUPPORT_TX_BACKLOG 1
#endif
#ifndef ATH_DEBUG
#define ATH_DEBUG 1
#endif
#ifndef ATH_SUPPORT_IBSS_HT
#define ATH_SUPPORT_IBSS_HT 1
#endif
#ifndef ATH_SUPPORT_IBSS_WMM
#define ATH_SUPPORT_IBSS_WMM 1
#endif
#ifndef ATH_SUPPORT_IBSS_PRIVATE_SECURITY
#define ATH_SUPPORT_IBSS_PRIVATE_SECURITY 1
#endif
#ifndef ATH_SUPPORT_AP_WDS_COMBO
#define ATH_SUPPORT_AP_WDS_COMBO 0
#endif
#ifndef UMAC_SUPPORT_QBSSLOAD
#define UMAC_SUPPORT_QBSSLOAD 1
#endif
#ifndef UMAC_SUPPORT_XBSSLOAD
#define UMAC_SUPPORT_XBSSLOAD 1
#endif
#ifndef UMAC_SUPPORT_ADMCTL
#define UMAC_SUPPORT_ADMCTL 1
#endif
#ifndef UMAC_SUPPORT_RRM
#define UMAC_SUPPORT_RRM 1
#endif
#ifndef UMAC_SUPPORT_RRM_MISC
#define UMAC_SUPPORT_RRM_MISC 0
#endif
#ifndef UMAC_SUPPORT_RRM_DEBUG
#define UMAC_SUPPORT_RRM_DEBUG 0
#endif
#ifndef UMAC_SUPPORT_WNM
#define UMAC_SUPPORT_WNM 1
#endif
#ifndef UMAC_SUPPORT_IE_UTILS
#define UMAC_SUPPORT_IE_UTILS 1
#endif
#ifndef UMAC_SUPPORT_QUIET
#define UMAC_SUPPORT_QUIET 1
#endif
#ifndef ATH_SUPPORT_ATHVAP_INFO
#define ATH_SUPPORT_ATHVAP_INFO 0
#endif
#ifndef ATH_RXBUF_RECYCLE
#define ATH_RXBUF_RECYCLE 0
#endif
#ifndef ATH_SUPPORT_PAPRD
#define ATH_SUPPORT_PAPRD 1
#endif
#ifndef ATH_TRAFFIC_FAST_RECOVER
#define ATH_TRAFFIC_FAST_RECOVER 1
#endif
#ifndef ATH_SUPPORT_DYN_TX_CHAINMASK
#define ATH_SUPPORT_DYN_TX_CHAINMASK 1
#endif
#ifndef ATH_BT_COEX_3WIRE_MODE
#define ATH_BT_COEX_3WIRE_MODE 0
#endif
#ifndef ATH_SUPPORT_IBSS_PERSTA_HWKEY
#define ATH_SUPPORT_IBSS_PERSTA_HWKEY 1
#endif
#ifndef ATH_SUPPORT_IBSS_WPA2
#define ATH_SUPPORT_IBSS_WPA2 1
#endif
#ifndef ATH_SWRETRY
#define ATH_SWRETRY 1
#endif
#ifndef ATH_SUPPORT_IBSS_WPA2
#define ATH_SUPPORT_IBSS_WPA2 1
#endif
#ifndef UMAC_SUPPORT_APONLY
#define UMAC_SUPPORT_APONLY 1
#endif
#ifndef ATH_TX_COMPACT
#define ATH_TX_COMPACT 1
#endif
#ifndef QCA_OL_TX_CACHEDHDR
#define QCA_OL_TX_CACHEDHDR 1
#endif
#ifndef QCA_OL_TX_PDEV_LOCK
#define QCA_OL_TX_PDEV_LOCK 1
#endif
#ifndef QCA_OL_TX_MULTIQ_SUPPORT
#define QCA_OL_TX_MULTIQ_SUPPORT 1
#endif
#ifndef REO_DESC_DEFER_FREE
#define REO_DESC_DEFER_FREE 1
#endif
#ifndef QCA_OL_RX_MULTIQ_SUPPORT
#define QCA_OL_RX_MULTIQ_SUPPORT 1
#endif
#ifndef ATH_SUPPORT_TIDSTUCK_WAR
#define ATH_SUPPORT_TIDSTUCK_WAR 0
#endif
#ifndef ATH_SUPPORT_DSCP_OVERRIDE
#define ATH_SUPPORT_DSCP_OVERRIDE 1
#endif
#ifndef UMAC_SUPPORT_STA_STATS
#define UMAC_SUPPORT_STA_STATS 1
#endif
#ifndef UMAC_SUPPORT_STA_STATS_ENHANCEMENT
#define UMAC_SUPPORT_STA_STATS_ENHANCEMENT 1
#endif
#ifndef UMAC_SUPPORT_PERIODIC_PERFSTATS
#define UMAC_SUPPORT_PERIODIC_PERFSTATS 0
#endif
#ifndef UMAC_SUPPORT_CHANUTIL_MEASUREMENT
#define UMAC_SUPPORT_CHANUTIL_MEASUREMENT 1
#endif
#ifndef ATH_GEN_RANDOMNESS
#define ATH_GEN_RANDOMNESS 0
#endif
#ifndef UMAC_SUPPORT_PROXY_ARP
#define UMAC_SUPPORT_PROXY_ARP
#endif
#ifndef UMAC_SUPPORT_DGAF_DISABLE
#define UMAC_SUPPORT_DGAF_DISABLE
#endif
#ifndef UMAC_SUPPORT_HS20_L2TIF
#define UMAC_SUPPORT_HS20_L2TIF
#endif
#ifndef ATH_SUPPORT_HS20
#define ATH_SUPPORT_HS20 1
#endif
#ifndef UMAC_SUPPORT_STA_MODE
#define UMAC_SUPPORT_STA_MODE 0
#endif
#ifndef UMAC_SUPPORT_TXDATAPATH_NODESTATS
#define UMAC_SUPPORT_TXDATAPATH_NODESTATS 0
#endif
#ifndef UMAC_SUPPORT_ACFG
#define UMAC_SUPPORT_ACFG 1
#endif
#ifndef UMAC_SUPPORT_ACFG_RECOVERY
#define UMAC_SUPPORT_ACFG_RECOVERY 1
#endif
#ifndef ATH_11AC_TXCOMPACT
#define ATH_11AC_TXCOMPACT 1
#endif
#ifndef QCA_NSS_NWIFI_MODE
#define QCA_NSS_NWIFI_MODE 0
#endif
#ifndef QCA_OL_RX_BATCHMODE
#define QCA_OL_RX_BATCHMODE 1
#endif
#ifndef ATH_PERF_PWR_OFFLOAD
#define ATH_PERF_PWR_OFFLOAD 1
#endif
#ifndef ATH_SUPPORT_FW_RAM_DUMP_FOR_MIPS
#define ATH_SUPPORT_FW_RAM_DUMP_FOR_MIPS 0
#endif
#ifndef WMI_RECORDING
#define WMI_RECORDING 0
#endif
#ifndef ATH_OL_11AC_DMA_BURST
#define ATH_OL_11AC_DMA_BURST 1
#endif
#ifndef ATH_OL_11AC_MAC_AGGR_DELIM
#define ATH_OL_11AC_MAC_AGGR_DELIM 0
#endif
#ifndef ATH_HOST_RX_PHY_ERROR
#define ATH_HOST_RX_PHY_ERROR 0
#endif
#ifndef AH_NEED_TX_DATA_SWAP
#define AH_NEED_TX_DATA_SWAP 0
#endif
#ifndef AH_NEED_RX_DATA_SWAP
#define AH_NEED_RX_DATA_SWAP 0
#endif
#ifndef PERE_IP_HDR_ALIGNMENT_WAR
#define PERE_IP_HDR_ALIGNMENT_WAR 1
#endif
#ifndef ATH_SUPPORT_WRAP
#define ATH_SUPPORT_WRAP 1
#endif
#ifndef ATH_PROXY_NOACK_WAR
#define ATH_PROXY_NOACK_WAR 1
#endif
#ifndef ATH_VAP_DELETE_ON_RMMOD
#define ATH_VAP_DELETE_ON_RMMOD 1
#endif
#ifndef WLAN_FEATURE_FASTPATH
#define WLAN_FEATURE_FASTPATH 1
#endif
#ifndef ATH_SUPPORT_4SS
#define ATH_SUPPORT_4SS 1
#endif
#ifndef QCA_SUPPORT_5SS_TO_8SS
#define QCA_SUPPORT_5SS_TO_8SS 1
#endif
#ifndef ATH_SUPPORT_DEFERRED_NODE_CLEANUP
#define ATH_SUPPORT_DEFERRED_NODE_CLEANUP 1
#endif
#ifndef ATH_SUPPORT_KEYPLUMB_WAR
#define ATH_SUPPORT_KEYPLUMB_WAR 1
#endif
#ifndef QCA_NSS_PLATFORM
#define QCA_NSS_PLATFORM 1
#endif
#ifndef QCA_NSS_WIFI_OFFLOAD_SUPPORT
#define QCA_NSS_WIFI_OFFLOAD_SUPPORT 1
#endif
#ifndef QCA_HOST_MODE_WIFI_DISABLED
#define QCA_HOST_MODE_WIFI_DISABLED 1
#endif
#ifndef QCA_NSS_WIFILI_OFFLOAD_SUPPORT
#define QCA_NSS_WIFILI_OFFLOAD_SUPPORT 1
#endif
#ifndef QCA_NSS_WIFI_2_0_OFFLOAD_SUPPORT
#define QCA_NSS_WIFI_2_0_OFFLOAD_SUPPORT 1
#endif
#ifndef UMAC_VOW_DEBUG
#define UMAC_VOW_DEBUG 1
#endif
#ifndef RX_DEBUG
#define RX_DEBUG 1
#endif
#ifndef DUMP_FW_RAM
#define DUMP_FW_RAM 1
#endif
#ifndef DBGLOG_WQ_BASED
#define DBGLOG_WQ_BASED 1
#endif
#ifndef HTT_RX_DESC_ALIGN_RESERVED
#define HTT_RX_DESC_ALIGN_RESERVED 0
#endif
#ifndef ATH_SUPPORT_CE_BARRIER
#define ATH_SUPPORT_CE_BARRIER 0
#endif
#ifndef LIMIT_RXBUF_LEN_4K
#define LIMIT_RXBUF_LEN_4K 0
#endif
#ifndef QCA_OL_VLAN_WAR
#define QCA_OL_VLAN_WAR 1
#endif
#ifndef AR900B_IP1_EMU_HACK
#define AR900B_IP1_EMU_HACK 0
#endif
#ifndef BEELINER_HOST_FPGA_FLAG
#define BEELINER_HOST_FPGA_FLAG 0
#endif
#ifndef IPQ4019_EMU
#define IPQ4019_EMU 0
#endif
#ifndef QCA_OL_SUPPORT_RAWMODE_TXRX
#define QCA_OL_SUPPORT_RAWMODE_TXRX 0
#endif
#ifndef QCA_OL_SUPPORT_RAWMODE_AR900B_BUFFCOALESCE
#define QCA_OL_SUPPORT_RAWMODE_AR900B_BUFFCOALESCE 0
#endif
#ifndef QCA_RAWMODE_OPTIMIZATION_CONFIG
#define QCA_RAWMODE_OPTIMIZATION_CONFIG 0
#endif
#ifndef QCA_SUPPORT_RAWMODE_PKT_SIMULATION
#define QCA_SUPPORT_RAWMODE_PKT_SIMULATION 0
#endif
#ifndef PCI_INTERRUPT_WAR_ENABLE
#define PCI_INTERRUPT_WAR_ENABLE 0
#endif
#ifndef ATH_MCAST_HOST_INSPECT
#define ATH_MCAST_HOST_INSPECT 0
#endif
#ifndef MCAST_ENHANCE_NO_CONSISTENT_MEM
#define MCAST_ENHANCE_NO_CONSISTENT_MEM 1
#endif
#ifndef ATH_SUPPORT_FIPS
#define ATH_SUPPORT_FIPS 1
#endif
#ifndef ATH_SUPPORT_MGMT_TX_STATUS
#define ATH_SUPPORT_MGMT_TX_STATUS 1
#endif
#ifndef ENHANCED_STATS
#define ENHANCED_STATS 1
#endif
#ifndef PEER_CACHEING_HOST_ENABLE
#define PEER_CACHEING_HOST_ENABLE 1
#endif
#ifndef QCA_AIRTIME_FAIRNESS
#define QCA_AIRTIME_FAIRNESS 1
#endif
#ifndef QCA_DFS_COMPONENT_ENABLE
#define QCA_DFS_COMPONENT_ENABLE 1
#endif
#ifndef WLAN_DFS_PARTIAL_OFFLOAD
#define WLAN_DFS_PARTIAL_OFFLOAD 1
#endif
#ifndef WLAN_DFS_FULL_OFFLOAD
#define WLAN_DFS_FULL_OFFLOAD 1
#endif
#ifndef HOST_DFS_SPOOF_TEST
#define HOST_DFS_SPOOF_TEST 1
#endif
#ifndef QCA_DFS_BANGRADAR
#define QCA_DFS_BANGRADAR 1
#endif
#ifndef QCA_SUPPORT_DFS_CAC
#define QCA_SUPPORT_DFS_CAC 1
#endif
#ifndef QCA_DFS_NOL_OFFLOAD
#define QCA_DFS_NOL_OFFLOAD 1
#endif
#ifndef QCA_LTEU_SUPPORT
#define QCA_LTEU_SUPPORT 1
#endif
#ifndef QCA_SUPPORT_SON
#define QCA_SUPPORT_SON 1
#endif
#ifndef QCA_SUPPORT_CP_STATS
#define QCA_SUPPORT_CP_STATS 1
#endif
#ifndef QCA_SUPPORT_SSID_STEERING
#define QCA_SUPPORT_SSID_STEERING 1
#endif
#ifndef ATH_SUPPORT_MBO
#define ATH_SUPPORT_MBO 1
#endif
#ifndef QCA_PARTNER_DIRECTLINK_RX
#define QCA_PARTNER_DIRECTLINK_RX 0
#endif
#ifndef QCA_PARTNER_DIRECTLINK_TX
#define QCA_PARTNER_DIRECTLINK_TX 0
#endif
#ifndef QCA_PARTNER_CBM_DIRECTPATH
#define QCA_PARTNER_CBM_DIRECTPATH 0
#endif
#ifndef ATH_SUPPORT_CODESWAP
#define ATH_SUPPORT_CODESWAP 1
#endif
#ifndef DEFAULT_BOARD_DATA
#define DEFAULT_BOARD_DATA 1
#endif
#ifndef ATH_CHANNEL_BLOCKING
#define ATH_CHANNEL_BLOCKING 1
#endif
#ifndef REMOVE_INIT_DEBUG_CODE
#define REMOVE_INIT_DEBUG_CODE 1
#endif
#ifndef FEATURE_NAPI
#define FEATURE_NAPI 1
#endif
#ifndef FEATURE_TSO
#define FEATURE_TSO 1
#endif
#ifndef ACFG_NETLINK_TX
#define ACFG_NETLINK_TX 1
#endif
#ifndef CE_HW_IDX_DEBUG
#define CE_HW_IDX_DEBUG 1
#endif
#ifndef REMOTE_PKTLOG_SUPPORT
#define REMOTE_PKTLOG_SUPPORT 0
#endif
#ifndef QCN_IE
#define QCN_IE 1
#endif
#ifndef QLD
#define QLD 1
#endif
#ifndef QCA_SUPPORT_GPR
#define QCA_SUPPORT_GPR 1
#endif
#ifndef QCN_ESP_IE
#define QCN_ESP_IE 1
#endif
#ifndef QCA_ENH_V3_STATS_SUPPORT
#define QCA_ENH_V3_STATS_SUPPORT 1
#endif
#ifndef HTT_STATS_ENABLE
#define HTT_STATS_ENABLE 1
#endif
#ifndef FEATURE_NAC_RSSI
#define FEATURE_NAC_RSSI 1
#endif
#ifndef PEER_FLOW_CONTROL
#define PEER_FLOW_CONTROL 1
#endif
#ifndef PEER_FLOW_CONTROL_HOST_SCHED
#define PEER_FLOW_CONTROL_HOST_SCHED 0
#endif
#ifndef PEER_FLOW_CONTROL_DEBUG
#define PEER_FLOW_CONTROL_DEBUG 0
#endif
#ifndef PEER_FLOW_CONTROL_FORCED_MODE0
#define PEER_FLOW_CONTROL_FORCED_MODE0 0
#endif
#ifndef MIPS_LOW_PERF_SUPPORT
#define MIPS_LOW_PERF_SUPPORT 0
#endif
#ifndef ATH_SUPPORT_DYNAMIC_VENDOR_IE
#define ATH_SUPPORT_DYNAMIC_VENDOR_IE 1
#endif
#ifndef QCA_LOWMEM_CONFIG
#define QCA_LOWMEM_CONFIG 1
#endif
#ifndef ATH_SUPPORT_NAC
#define ATH_SUPPORT_NAC 1
#endif
#ifndef ATH_SUPPORT_NAC_RSSI
#define ATH_SUPPORT_NAC_RSSI 1
#endif
#ifndef QCA_MULTIPASS_SUPPORT
#define QCA_MULTIPASS_SUPPORT 1
#endif
#ifndef CFG_MAX_TMPNODES
#define CFG_MAX_TMPNODES 64
#endif
#ifndef WLAN_ENABLE_ERROR_ON_WARN
#define WLAN_ENABLE_ERROR_ON_WARN 1
#endif
#ifndef NO_RX_PKT_HDR_TLV
#define NO_RX_PKT_HDR_TLV 1
#endif
#ifndef WLAN_PEER_JITTER
#define WLAN_PEER_JITTER 1
#endif
#ifndef ATH_ACS_DEBUG_SUPPORT
#define ATH_ACS_DEBUG_SUPPORT 1
#endif
#ifndef WLAN_SUPPORT_RF_CHARACTERIZATION
#define WLAN_SUPPORT_RF_CHARACTERIZATION 1
#endif
#ifndef WIFI_MEM_MANAGER_SUPPORT
#define WIFI_MEM_MANAGER_SUPPORT 1
#endif
#ifndef DBDC_REPEATER_SUPPORT
#define DBDC_REPEATER_SUPPORT 1
#endif
#ifndef FW_CODE_SIGN
#define FW_CODE_SIGN 0
#endif
#ifndef OL_STATS_WORK_QUEUE
#define OL_STATS_WORK_QUEUE 1
#endif
#ifndef DBG_LVL_MAC_FILTERING
#define DBG_LVL_MAC_FILTERING 0
#endif
#ifndef ATH_TXQ_DRAIN_DEFERRED
#define ATH_TXQ_DRAIN_DEFERRED 0
#endif
#ifndef QCA_11AX_STUB_SUPPORT
#define QCA_11AX_STUB_SUPPORT 1
#endif
#ifndef DYNAMIC_BEACON_SUPPORT
#define DYNAMIC_BEACON_SUPPORT 1
#endif
#ifndef CONFIG_WIN
#define CONFIG_WIN 1
#endif
#ifndef DATA_CE_SW_INDEX_NO_INLINE_UPDATE
#define DATA_CE_SW_INDEX_NO_INLINE_UPDATE 1
#endif
#ifndef QCA_PEER_MULTIQ_SUPPORT
#define QCA_PEER_MULTIQ_SUPPORT 1
#endif
#ifndef QCA_PEER_EXT_STATS
#define QCA_PEER_EXT_STATS 1
#endif
#ifndef PANIC_ON_BUG
#define PANIC_ON_BUG 1
#endif
#ifndef WMI_TLV_AND_NON_TLV_SUPPORT
#define WMI_TLV_AND_NON_TLV_SUPPORT 1
#endif
#ifndef CONFIG_ATH_PCIE_MAX_PERF
#define CONFIG_ATH_PCIE_MAX_PERF 1
#endif
#ifndef HIF_PCI
#define HIF_PCI
#endif
#ifndef ATH_DIRECT_ATTACH
#define ATH_DIRECT_ATTACH 1
#endif
#ifndef QCA_OL_TX_CACHEDHDR
#define QCA_OL_TX_CACHEDHDR 1
#endif
#ifndef ATH_TX_OVERFLOW_IND
#define ATH_TX_OVERFLOW_IND 1
#endif
#ifndef ATH_SUPPORT_11N_CHANWIDTH_SWITCH
#define ATH_SUPPORT_11N_CHANWIDTH_SWITCH 1
#endif
#ifndef ATH_NON_BEACON_AP
#define ATH_NON_BEACON_AP 1
#endif
#ifndef ATH_DATA_TX_INFO_EN
#define ATH_DATA_TX_INFO_EN 1
#endif
#ifndef WMI_INTERFACE_EVENT_LOGGING
#define WMI_INTERFACE_EVENT_LOGGING 1
#endif
#ifndef WMI_INTERFACE_EVENT_LOGGING_DYNAMIC_ALLOC
#define WMI_INTERFACE_EVENT_LOGGING_DYNAMIC_ALLOC 1
#endif
#ifndef WLAN_HEADERS
#define WLAN_HEADERS 1
#endif
#ifndef SUPPORT_11N
#define SUPPORT_11N 1
#endif
#ifndef SUPPORT_VHT
#define SUPPORT_VHT 1
#endif
#ifndef CONVERGED_SW
#define CONVERGED_SW 1
#endif
#ifndef ATH_PERF_PWR_OFFLOAD
#define ATH_PERF_PWR_OFFLOAD 1
#endif
#ifndef TEMP_AGGR_CFG
#define TEMP_AGGR_CFG 1
#endif
#ifndef AR900B
#define AR900B 1
#endif
#ifndef ATH_SUPPORT_MCAST2UCAST
#define ATH_SUPPORT_MCAST2UCAST
#endif
#ifndef QCA_OL_TX_CACHEDHDR
#define QCA_OL_TX_CACHEDHDR 1
#endif
#ifndef DUMP_FW_RAM
#define DUMP_FW_RAM 1
#endif
#ifndef WDI_EVENT_ENABLE
#define WDI_EVENT_ENABLE
#endif
#ifndef WAR_DISABLE_MU_2x2_STA
#define WAR_DISABLE_MU_2x2_STA 0
#endif
#ifndef ENABLE_10_4_FW_HDR
#define ENABLE_10_4_FW_HDR 0
#endif
#ifndef CONFIG_160MHZ_SUPPORT
#define CONFIG_160MHZ_SUPPORT 1
#endif
#ifndef QCA_WIFI_QCA5018
#define QCA_WIFI_QCA5018 1
#endif
#ifndef QCA5018_HEADERS_DEF
#define QCA5018_HEADERS_DEF 1
#endif
#ifndef WMI_TLV_AND_NON_TLV_SUPPORT
#define WMI_TLV_AND_NON_TLV_SUPPORT 1
#endif
#ifndef WLAN_CONV_CRYPTO_SUPPORTED
#define WLAN_CONV_CRYPTO_SUPPORTED 1
#endif
#ifndef WLAN_CRYPTO_AES
#define WLAN_CRYPTO_AES 1
#endif
#ifndef WLAN_OFFCHAN_TXRX_ENABLE
#define WLAN_OFFCHAN_TXRX_ENABLE 1
#endif
#ifndef DIRECT_BUF_RX_ENABLE
#define DIRECT_BUF_RX_ENABLE 1
#endif
#ifndef CONFIGURE_ACL_HOSTAPD
#define CONFIGURE_ACL_HOSTAPD 0
#endif
#ifndef WLAN_RX_PKT_CAPTURE_ENH
#define WLAN_RX_PKT_CAPTURE_ENH 1
#endif
#ifndef FEATURE_PERPKT_INFO
#define FEATURE_PERPKT_INFO 1
#endif
#ifndef FEATURE_AST
#define FEATURE_AST 1
#endif
#ifndef FEATURE_MEC
#define FEATURE_MEC 1
#endif
#ifndef FEATURE_AST
#define FEATURE_AST 1
#endif
#ifndef FEATURE_MEC
#define FEATURE_MEC 1
#endif
#ifndef FEATURE_WDS
#define FEATURE_WDS 1
#endif
#ifndef DUP_RX_DESC_WAR
#define DUP_RX_DESC_WAR 1
#endif
#ifndef DUP_RX_DESC_WAR
#define DUP_RX_DESC_WAR 1
#endif
#ifndef WLAN_OBJMGR_DEBUG
#define WLAN_OBJMGR_DEBUG 1
#endif
#ifndef CONFIG_CNSS2_SUPPORT
#define CONFIG_CNSS2_SUPPORT 1
#endif
#ifndef DP_HAL_MULTIWINDOW_DIRECT_ACCESS
#define DP_HAL_MULTIWINDOW_DIRECT_ACCESS 1
#endif
#ifndef QCA_WIFI_QCN9000
#define QCA_WIFI_QCN9000 1
#endif
#ifndef QCN9000_HEADERS_DEF
#define QCN9000_HEADERS_DEF 1
#endif
#ifndef WMI_TLV_AND_NON_TLV_SUPPORT
#define WMI_TLV_AND_NON_TLV_SUPPORT 1
#endif
#ifndef QCA_WIFI_QCN6122
#define QCA_WIFI_QCN6122 1
#endif
#ifndef QCN6122_HEADERS_DEF
#define QCN6122_HEADERS_DEF 1
#endif
#ifndef WMI_TLV_AND_NON_TLV_SUPPORT
#define WMI_TLV_AND_NON_TLV_SUPPORT 1
#endif
#ifndef WLAN_RX_HASH
#define WLAN_RX_HASH 1
#endif
#ifndef CONFIG_PLD_PCIE_CNSS
#define CONFIG_PLD_PCIE_CNSS 1
#endif
#ifndef WLAN_SUPPORT_FILS
#define WLAN_SUPPORT_FILS 1
#endif
#ifndef WLAN_CRYPTO_SUPPORT_FILS
#define WLAN_CRYPTO_SUPPORT_FILS 1
#endif
#ifndef QCA_CONFIG_SMP
#define QCA_CONFIG_SMP 1
#endif
#ifndef ATH_PARAMETER_API
#define ATH_PARAMETER_API 0
#endif
#ifndef WLAN_WARN_ON_ASSERT
#define WLAN_WARN_ON_ASSERT 1
#endif
#ifndef WLAN_DEBUGFS
#define WLAN_DEBUGFS 1
#endif
#ifndef QDF_NBUF_GLOBAL_COUNT
#define QDF_NBUF_GLOBAL_COUNT 1
#endif
#ifndef WLAN_SUPPORT_TWT
#define WLAN_SUPPORT_TWT 1
#endif
#ifndef VDEV_SM_LOCK_SUPPORT
#define VDEV_SM_LOCK_SUPPORT 1
#endif
#ifndef ATH_DATABUS_ERROR_RESET_LOCK_3PP
#define ATH_DATABUS_ERROR_RESET_LOCK_3PP 0
#endif
#ifndef ATH_POWERSAVE_WAR
#define ATH_POWERSAVE_WAR 1
#endif
#ifndef QDF_TRACE_PRINT_ENABLE
#define QDF_TRACE_PRINT_ENABLE 1
#endif
#ifndef WLAN_LOG_FATAL
#define WLAN_LOG_FATAL 1
#endif
#ifndef WLAN_LOG_ERROR
#define WLAN_LOG_ERROR 1
#endif
#ifndef WLAN_LOG_WARN
#define WLAN_LOG_WARN 1
#endif
#ifndef WLAN_LOG_INFO
#define WLAN_LOG_INFO 1
#endif
#ifndef WLAN_LOG_DEBUG
#define WLAN_LOG_DEBUG 1
#endif
#ifndef WLAN_LOG_ENTER
#define WLAN_LOG_ENTER 1
#endif
#ifndef WLAN_LOG_EXIT
#define WLAN_LOG_EXIT 1
#endif
#ifndef AST_HKV1_WORKAROUND
#define AST_HKV1_WORKAROUND 1
#endif
#ifndef EBUG_PROFILE
#define EBUG_PROFILE 0
#endif
#ifndef WLAN_OBJMGR_REF_ID_DEBUG
#define WLAN_OBJMGR_REF_ID_DEBUG 1
#endif
#ifndef QCA_TGT_FW_IRAM_DUMP_ENABLE
#define QCA_TGT_FW_IRAM_DUMP_ENABLE 1
#endif
#ifndef QCA_WIFI_FTM
#define QCA_WIFI_FTM 1
#endif
#ifndef QCA_WIFI_FTM_IOCTL
#define QCA_WIFI_FTM_IOCTL 1
#endif
#ifndef QCA_WIFI_FTM_NL80211
#define QCA_WIFI_FTM_NL80211 0
#endif
#ifndef OL_ATH_SMART_LOGGING
#define OL_ATH_SMART_LOGGING 1
#endif
#ifndef QCA_OL_DMS_WAR
#define QCA_OL_DMS_WAR 1
#endif
#ifndef QCA_DFS_NOL_VAP_RESTART
#define QCA_DFS_NOL_VAP_RESTART 1
#endif
#ifndef OBSS_PD
#define OBSS_PD 1
#endif
#ifndef WLAN_SER_DEBUG
#define WLAN_SER_DEBUG 1
#endif
#ifndef QCA_6290_AP_MODE
#define QCA_6290_AP_MODE 1
#endif
#ifndef QCA_HIF_HIA_EXTND
#define QCA_HIF_HIA_EXTND 1
#endif
#ifndef WMI_DBR_SUPPORT
#define WMI_DBR_SUPPORT 1
#endif
#ifndef WMI_ATF_SUPPORT
#define WMI_ATF_SUPPORT 1
#endif
#ifndef WMI_AP_SUPPORT
#define WMI_AP_SUPPORT 1
#endif
#ifndef QCA_MEM_ATTACH_ON_WIFI3
#define QCA_MEM_ATTACH_ON_WIFI3 1
#endif
#ifndef WIFI_TARGET_TYPE_3_0
#define WIFI_TARGET_TYPE_3_0 1
#endif
#ifndef SUPPORT_11AX
#define SUPPORT_11AX 1
#endif
#ifndef DP_RATETABLE_SUPPORT
#define DP_RATETABLE_SUPPORT 1
#endif
#ifndef QCA_TX_LIMIT_CHECK
#define QCA_TX_LIMIT_CHECK 1
#endif
#ifndef ENHANCED_OS_ABSTRACTION
#define ENHANCED_OS_ABSTRACTION 1
#endif
#ifndef WLAN_BCN_RATECODE_ENABLE
#define WLAN_BCN_RATECODE_ENABLE 1
#endif
#ifndef ENABLE_HOST_TO_TARGET_CONVERSION
#define ENABLE_HOST_TO_TARGET_CONVERSION 1
#endif
#ifndef VDEV_ASSERT_MANAGEMENT
#define VDEV_ASSERT_MANAGEMENT 1
#endif
#ifndef HIF_CE_DEBUG_DATA_DYNAMIC_BUF
#define HIF_CE_DEBUG_DATA_DYNAMIC_BUF 1
#endif
#ifndef CONFIG_NBUF_AP_PLATFORM
#define CONFIG_NBUF_AP_PLATFORM 1
#endif
#ifndef CONFIG_AP_PLATFORM
#define CONFIG_AP_PLATFORM 1
#endif
#ifndef WLAN_CRYPTO_MAX_VLANKEYIX
#define WLAN_CRYPTO_MAX_VLANKEYIX 128
#endif
#ifndef MGMT_FRAME_RX_DECRYPT_ERROR
#define MGMT_FRAME_RX_DECRYPT_ERROR 1
#endif
#ifndef QCA_DISABLE_TX_PKT_TRACE
#define QCA_DISABLE_TX_PKT_TRACE 1
#endif
#ifndef HOST_OPCLASS
#define HOST_OPCLASS 1
#endif
#ifndef QCA_HOST_ADD_11AX_MODE_WAR
#define QCA_HOST_ADD_11AX_MODE_WAR 1
#endif
#ifndef WLAN_SCHED_HISTORY_SIZE
#define WLAN_SCHED_HISTORY_SIZE 100
#endif
#ifndef QCA_SUPPORT_EMA_EXT
#define QCA_SUPPORT_EMA_EXT 1
#endif
#ifndef QCA_OL_TX_LOCK_LESS_ACCESS
#define QCA_OL_TX_LOCK_LESS_ACCESS 1
#endif
#ifndef QCA_DP_TX_DESC_FAST_COMP_ENABLE
#define QCA_DP_TX_DESC_FAST_COMP_ENABLE 1
#endif
#ifndef QCA_CACHED_RING_DESC
#define QCA_CACHED_RING_DESC 1
#endif
#ifndef QCA_SUPPORT_PEER_ISOLATION
#define QCA_SUPPORT_PEER_ISOLATION 1
#endif
#ifndef FEATURE_BLACKLIST_MGR
#define FEATURE_BLACKLIST_MGR 1
#endif
#ifndef WLAN_MAX_LOGS_PER_SEC
#define WLAN_MAX_LOGS_PER_SEC 1000
#endif
#ifndef WMI_INTERFACE_SEQUENCE_CHECK
#define WMI_INTERFACE_SEQUENCE_CHECK 1
#endif
#ifndef CONFIG_HOST_FIND_CHAN
#define CONFIG_HOST_FIND_CHAN 1
#endif
#ifndef WLAN_CM_USE_SPINLOCK
#define WLAN_CM_USE_SPINLOCK 1
#endif
#ifndef FEATURE_CM_ENABLE
#define FEATURE_CM_ENABLE 1
#endif
#ifndef WLAN_FEATURE_HOST_ROAM
#define WLAN_FEATURE_HOST_ROAM 1
#endif
#ifndef WLAN_QWRAP_LEGACY
#define WLAN_QWRAP_LEGACY 0
#endif
#ifndef HAL_DISABLE_NON_BA_2K_JUMP_ERROR
#define HAL_DISABLE_NON_BA_2K_JUMP_ERROR 1
#endif
#ifndef WLAN_DP_PENDING_MEM_FLUSH
#define WLAN_DP_PENDING_MEM_FLUSH 1
#endif
#ifndef ATH_TX99_DIAG
#define ATH_TX99_DIAG 1
#endif
#ifndef USE_PLATFORM_FRAMEWORK
#define USE_PLATFORM_FRAMEWORK
#endif
#endif
